name: Run Jupyter Notebook

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions: write-all

jobs:
  execute-notebook:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./.github/workflows/requirements.txt

    # Step 4: Execute the Jupyter notebook
    - name: Execute notebook
      run: |
        jupyter nbconvert --to notebook --execute --ExecutePreprocessor.cwd=./documentation/CI_CD_results/signals_CICD_last_run ./documentation/playground_mr0/mr0_FID_seq.ipynb --output executed_notebook.ipynb --output-dir ./documentation/CI_CD_results/executed_notebooks_CICD_last_run

    # Step 6: show what files are going to be deleted
    - name: Delete aux files
      run: |
        find ./documentation/CI_CD_results/signals_CICD_last_run -maxdepth 1 -type f ! -name "*.npz" ! -name "README" -exec echo "Would delete: {}" \;
        
    # Step 7: Delete all auxiliary files
    - name: Delete aux files
      run: |
        find ./documentation/CI_CD_results/signals_CICD_last_run -maxdepth 1 -type f ! -name "*.npz" ! -name "README" -exec rm -f {} \;
        
    # ==================================================
    #                  PUSH CHANGES
    # ==================================================
    - name: Push changes
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Accessing the secret
      run: |
          git config --local user.email "playgroundmr0@gmail.com"
          git config --local user.name "playground-mr0"
          git add .
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "There are changes to commit."
            git commit -m "Automated commit"
            git push origin $GITHUB_REF
          else
            echo "No changes to commit."
          fi

    # ==================================================
    #      COMPARISON GROUND TRUTH - LAST PUSH
    # ==================================================
    
    #- name: Run specific test
    #  run: |
    #      pytest ./CI_CD_results/Comparison_results_workflow.py
